# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170814_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='datum',
            name='id',
        ),
        migrations.RemoveField(
            model_name='datum',
            name='location',
        ),
        migrations.AlterField(
            model_name='datum',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='raw',
            name='datum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='webapp.Datum'),
        ),
    ]
