# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170822_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='hdfs_dir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
