# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170822_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('DB', 'Database Creation Job'), ('GS', 'Genomic Search Job')], default='DB', max_length=2),
        ),
    ]
