# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170814_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datum',
            new_name='Dataset',
        ),
    ]
