# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_job_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='hdfs_dir',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AlterField(
            model_name='raw',
            name='dataset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='webapp.Dataset'),
        ),
        migrations.AddField(
            model_name='database',
            name='jobs',
            field=models.ManyToManyField(null=True, related_name='databases', to='webapp.Job'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='databases',
            field=models.ManyToManyField(null=True, related_name='datasets', to='webapp.Database'),
        ),
        migrations.AddField(
            model_name='raw',
            name='database',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='webapp.Database'),
        ),
    ]
