# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 03:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170815_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='backend_job',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='jobs',
            field=models.ManyToManyField(null=True, related_name='datasets', to='webapp.Job'),
        ),
    ]
