# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170822_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='databases',
            field=models.ManyToManyField(null=True, related_name='datasets', to='webapp.Database'),
        ),
    ]
