# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170822_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='jobs',
            field=models.ManyToManyField(related_name='databases', to='webapp.Job'),
        ),
    ]
